import type { Metadata } from "next";
import "./globals.css";
import { quicksand } from "@/components/ui/fonts";
import Header from "@/components/ui/header/header";
import Footer from "@/components/ui/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${quicksand.className} antialiased`}>
        <Header />
        <main className="py-[55px] xl:pt-[103px] w-full px-3 xl:px-20 max-w-8xl mx-auto border-t">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
